disabled_rules:
  - trailing_whitespace
  - switch_case_on_newline
  - trailing_newline
  - cyclomatic_complexity

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces

included:
  - Sources
  - Tests

excluded:
  - .build
  - tarot-model

line_length:
  warning: 160
  error: 200

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 80
  error: 120

file_length:
  warning: 500
  error: 800

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - i
    - j
    - a
    - r
    - g
    - b

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50