name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9"
        
    - name: Run Tests
      run: swift test --enable-code-coverage
      
    - name: Generate Code Coverage Report
      run: |
        xcrun llvm-cov export \
          .build/debug/SwiftTarotCardsPackageTests.xctest/Contents/MacOS/SwiftTarotCardsPackageTests \
          -instr-profile=.build/debug/codecov/default.profdata \
          -format=lcov > coverage.lcov
      continue-on-error: true
      
  test-linux:
    runs-on: ubuntu-latest
    container: swift:5.9-jammy
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Run Tests on Linux
      run: swift test
      
  test-ios-simulator:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.4.0'
        
    - name: Generate Xcode Project
      run: swift package generate-xcodeproj
      
    - name: Test iOS Simulator
      run: |
        xcodebuild test \
          -project SwiftTarotCards.xcodeproj \
          -scheme SwiftTarotCards-Package \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -enableCodeCoverage YES
      continue-on-error: true